name: Build Unrott
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build IPA
        run: |
          xcodebuild -project "Unrott/Unrott.xcodeproj" \
          -scheme Unrott \
          -configuration Release \
          -sdk iphoneos \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CLEAN build

      - name: Prepare Payload
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/Unrott.app Payload/
          zip -r Unrott.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unrott-IPA
          path: Unrott.ipa
